# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
    - sdk/resourcemanager/storSimple1200Series/armstorSimple1200Series/

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
    - sdk/resourcemanager/storSimple1200Series/armstorSimple1200Series/

stages:
- template: /eng/pipelines/templates/jobs/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: 'resourcemanager/storSimple1200Series/armstorSimple1200Series'
